require_relative "equipment_hire/errors"
require_relative "equipment_hire/product"
require_relative "equipment_hire/hire_item"
require_relative "equipment_hire/hire_period"
require_relative "equipment_hire/hire_request"
require_relative "equipment_hire/catalog"
require_relative "equipment_hire/stock_item"
require_relative "equipment_hire/inventory"
require_relative "equipment_hire/quote_result"
require_relative "equipment_hire/quote_calculator"
require_relative "equipment_hire/booking"
require_relative "equipment_hire/booking_confirmer"

require_relative "equipment_hire/pricing/standard"
require_relative "equipment_hire/pricing/weekend"
require_relative "equipment_hire/pricing/member"

require_relative "equipment_hire/delivery/collection"
require_relative "equipment_hire/delivery/local"
require_relative "equipment_hire/delivery/distance"
require_relative "equipment_hire/delivery/corporate"

require_relative "equipment_hire/services/system_clock"
require_relative "equipment_hire/services/payment_gateway"
require_relative "equipment_hire/services/notifier"
